version: '3'
services:
  debian:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /root/NTRUEncrypt
    tty: true
    volumes:
      - projectroot:/root/NTRUEncrypt

volumes:
  projectroot:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VOLUME_PATH}

